SELECT  DISTINCT CITY FROM STATION 
WHERE (NOT(CITY LIKE "a%" OR CITY LIKE "i%" OR CITY LIKE "u%" OR CITY LIKE "e%" OR CITY LIKE "o%")) 
OR (NOT(CITY LIKE "%a" OR CITY LIKE "%i" OR CITY LIKE "%u" OR CITY LIKE "%e" OR CITY LIKE "%o")) ORDER BY CITY;